import Head from 'next/head'
import Image from 'next/image'
import { Featured } from '../components/Featured'
import { ProductsList } from '../components/ProductsList'
import axios from "axios";

export default function Home({productsList}) {

  return (
    <div>
      <Head>
        <title>Sweetie Bell</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Featured/>
      <ProductsList productsList = {productsList} />
    </div>
  )
}
export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      productsList: res.data,
    }
  }
}