import Head from 'next/head'
import Image from 'next/image'
import { Featured } from '../components/Featured'
import { ProductsList } from '../components/ProductsList'
import axios from "axios";
import { useState } from 'react';
import Add from '../components/Add';
import AddButton from '../components/AddButton';


export default function Home({productsList, admin}) {
  const [close, setClose] = useState(true)

  return (
    <div>
      <Head>
        <title>Sweetie Bell</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Featured/>
      {<AddButton setClose={setClose} />}
      <ProductsList productsList = {productsList} />
      {!close && <Add setClose={setClose}/>}
    </div>
  )
}
export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookie || ""
  let admin = false

  if(myCookie.token === process.env.TOKEN){
    admin = true
  }
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      productsList: res.data,
    }
  }
}